import 'package:get_it/get_it.dart';
import 'package:sail_ui/env.dart';
import 'package:sail_ui/sail_ui.dart';
import 'package:zside/providers/backend_zside_conf_provider.dart';

/// Provider for ZSide configuration settings.
/// In backend mode, uses BackendZSideConfProvider (RPC-backed).
/// In frontend mode, uses the file-based implementation directly.
class ZSideConfProvider extends GenericSidechainConfProvider {
  ZSideConfProvider._create();
  ZSideConfProvider.protected();

  static Future<ZSideConfProvider> create() async {
    if (Environment.backendManagesBinaries) {
      return BackendZSideConfProvider.create();
    }
    final instance = ZSideConfProvider._create();
    await instance.initialize();
    return instance;
  }

  @override
  String get appName => 'ZSide';

  @override
  String get configFileName => 'zside.conf';

  @override
  String getDataDir() => ZSide().datadir();

  @override
  List<String> get skippedCliKeys => ['network'];

  @override
  Map<String, String> getNetworkPorts(String network) {
    switch (network) {
      case 'regtest':
        return {
          'rpc-addr': '127.0.0.1:16098',
          'net-addr': '0.0.0.0:14098',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'mainnet':
        return {
          'rpc-addr': '127.0.0.1:26098',
          'net-addr': '0.0.0.0:24098',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'signet':
      default:
        return {
          'rpc-addr': '127.0.0.1:6098',
          'net-addr': '0.0.0.0:4098',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
    }
  }

  @override
  String getDefaultConfig() {
    String network = 'signet';
    try {
      final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
      network = switch (bitcoinConfProvider.network) {
        BitcoinNetwork.BITCOIN_NETWORK_SIGNET => 'signet',
        BitcoinNetwork.BITCOIN_NETWORK_REGTEST => 'regtest',
        BitcoinNetwork.BITCOIN_NETWORK_FORKNET => 'mainnet',
        _ => 'signet',
      };
    } catch (_) {}

    final ports = getNetworkPorts(network);

    return '''# ZSide Configuration - Generated by ZSide App
# These settings are converted to CLI arguments when ZSide starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Log level for file output
log-level-file=WARN

# Network (signet or regtest)
network=$network

# RPC server address
rpc-addr=${ports['rpc-addr']}

# P2P networking address
net-addr=${ports['net-addr']}

# Mainchain (Enforcer) gRPC connection URL
mainchain-grpc-url=${ports['mainchain-grpc-url']}
''';
  }
}
