package config

import (
	"fmt"
	"strconv"
	"strings"
)

const bitcoinConfVersionCommentPrefix = "# bitwindow-bitcoin-conf-version="

// BitcoinConfig represents a parsed Bitcoin Core configuration file.
// 1:1 port of sail_ui/lib/models/bitcoin_config.dart
type BitcoinConfig struct {
	GlobalSettings  map[string]string
	NetworkSettings map[string]map[string]string // "main", "test", "signet", "regtest"
	ConfigVersion   int
}

func NewBitcoinConfig() *BitcoinConfig {
	return &BitcoinConfig{
		GlobalSettings: make(map[string]string),
		NetworkSettings: map[string]map[string]string{
			"main":    {},
			"test":    {},
			"signet":  {},
			"regtest": {},
		},
		ConfigVersion: 0,
	}
}

// ParseBitcoinConfig parses bitcoin.conf content into a BitcoinConfig.
func ParseBitcoinConfig(content string) *BitcoinConfig {
	config := NewBitcoinConfig()
	var currentSection string

	lines := strings.Split(content, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Parse version comment for migration system
		if strings.HasPrefix(trimmed, bitcoinConfVersionCommentPrefix) {
			vStr := strings.TrimSpace(trimmed[len(bitcoinConfVersionCommentPrefix):])
			if v, err := strconv.Atoi(vStr); err == nil && v >= 0 {
				config.ConfigVersion = v
			}
			continue
		}

		// Skip empty lines and other comments
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Check for section header
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			section := trimmed[1 : len(trimmed)-1]
			if _, ok := config.NetworkSettings[section]; ok {
				currentSection = section
			}
			continue
		}

		// Parse key=value pairs
		eqIdx := strings.Index(trimmed, "=")
		if eqIdx > 0 {
			key := strings.TrimSpace(trimmed[:eqIdx])
			value := strings.TrimSpace(trimmed[eqIdx+1:])

			if currentSection != "" {
				config.NetworkSettings[currentSection][key] = value
			} else {
				config.GlobalSettings[key] = value
			}
		}
	}

	return config
}

// Serialize writes the config back to file format.
func (c *BitcoinConfig) Serialize() string {
	var b strings.Builder

	if c.ConfigVersion > 0 {
		fmt.Fprintf(&b, "%s%d\n\n", bitcoinConfVersionCommentPrefix, c.ConfigVersion)
	}

	b.WriteString("# Generated by BitWindow Bitcoin Configuration Editor\n")
	b.WriteString("# Feel free to edit this file, changes will be applied.\n\n")

	// Write global settings
	if len(c.GlobalSettings) > 0 {
		b.WriteString("# [common settings]\n")
		for key, value := range c.GlobalSettings {
			fmt.Fprintf(&b, "%s=%s\n", key, value)
		}
		b.WriteString("\n")
	}

	// Write network-specific settings
	sectionNames := map[string]string{
		"main":    "[main]",
		"test":    "[test]",
		"signet":  "[signet]",
		"regtest": "[regtest]",
	}
	sectionOrder := []string{"main", "test", "signet", "regtest"}

	for _, network := range sectionOrder {
		settings := c.NetworkSettings[network]
		if len(settings) > 0 {
			label := network
			if network == "main" {
				label = "mainnet"
			}
			fmt.Fprintf(&b, "# Options for %s only\n", label)
			fmt.Fprintf(&b, "%s\n", sectionNames[network])
			for key, value := range settings {
				fmt.Fprintf(&b, "%s=%s\n", key, value)
			}
			b.WriteString("\n")
		}
	}

	return b.String()
}

func (c *BitcoinConfig) GetSetting(key string, section ...string) string {
	if len(section) > 0 && section[0] != "" {
		if s, ok := c.NetworkSettings[section[0]]; ok {
			return s[key]
		}
		return ""
	}
	return c.GlobalSettings[key]
}

// GetEffectiveSetting returns the effective setting for a network (section overrides global).
func (c *BitcoinConfig) GetEffectiveSetting(key, network string) string {
	if s, ok := c.NetworkSettings[network]; ok {
		if v, exists := s[key]; exists {
			return v
		}
	}
	return c.GlobalSettings[key]
}

func (c *BitcoinConfig) SetSetting(key, value string, section ...string) {
	if len(section) > 0 && section[0] != "" {
		if s, ok := c.NetworkSettings[section[0]]; ok {
			s[key] = value
		}
	} else {
		c.GlobalSettings[key] = value
	}
}

func (c *BitcoinConfig) RemoveSetting(key string, section ...string) {
	if len(section) > 0 && section[0] != "" {
		if s, ok := c.NetworkSettings[section[0]]; ok {
			delete(s, key)
		}
	} else {
		delete(c.GlobalSettings, key)
	}
}

func (c *BitcoinConfig) HasSetting(key string, section ...string) bool {
	if len(section) > 0 && section[0] != "" {
		if s, ok := c.NetworkSettings[section[0]]; ok {
			_, exists := s[key]
			return exists
		}
		return false
	}
	_, exists := c.GlobalSettings[key]
	return exists
}
