package config

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/rs/zerolog"
)

const bitwindowEnforcerConfFilename = "bitwindow-enforcer.conf"

// EnforcerConfManager manages Enforcer daemon configuration.
// Port of the data/config logic from sail_ui/lib/providers/enforcer_conf_provider.dart.
type EnforcerConfManager struct {
	Config      *EnforcerConfig
	ConfigPath  string
	bitcoinConf *BitcoinConfManager
	log         zerolog.Logger
}

// NewEnforcerConfManager creates a new EnforcerConfManager and loads config.
func NewEnforcerConfManager(bitcoinConf *BitcoinConfManager, log zerolog.Logger) (*EnforcerConfManager, error) {
	m := &EnforcerConfManager{
		bitcoinConf: bitcoinConf,
		log:         log.With().Str("component", "enforcer-conf").Logger(),
	}
	if err := m.LoadConfig(); err != nil {
		return nil, fmt.Errorf("load enforcer config: %w", err)
	}
	// Sync node-rpc settings from bitcoin config
	if err := m.SyncFromBitcoinConf(); err != nil {
		m.log.Warn().Err(err).Msg("failed to sync enforcer config from bitcoin conf")
	}
	return m, nil
}

// LoadConfig loads or creates the enforcer configuration file.
func (m *EnforcerConfManager) LoadConfig() error {
	m.ConfigPath = m.getConfigPath()

	data, err := os.ReadFile(m.ConfigPath)
	if err == nil {
		m.Config = ParseEnforcerConfig(string(data))

		// Run migration: add zmq-sequence if missing
		if !m.Config.HasSetting("node-zmq-addr-sequence") {
			m.Config.SetSetting("node-zmq-addr-sequence", "tcp://127.0.0.1:29000")
			if writeErr := m.SaveConfig(); writeErr != nil {
				m.log.Warn().Err(writeErr).Msg("failed to save migrated enforcer config")
			}
		}
		return nil
	}

	if !os.IsNotExist(err) {
		return fmt.Errorf("read enforcer config: %w", err)
	}

	// Create default config
	content := m.GetDefaultConfig()
	m.Config = ParseEnforcerConfig(content)

	if mkErr := os.MkdirAll(filepath.Dir(m.ConfigPath), 0755); mkErr != nil {
		m.log.Error().Err(mkErr).Msg("failed to create enforcer config directory")
	} else if wErr := os.WriteFile(m.ConfigPath, []byte(content), 0644); wErr != nil {
		m.log.Error().Err(wErr).Str("path", m.ConfigPath).Msg("failed to write default enforcer config")
	} else {
		m.log.Info().Str("path", m.ConfigPath).Msg("created default enforcer config")
	}

	return nil
}

// GetDefaultConfig generates the default enforcer config content.
func (m *EnforcerConfManager) GetDefaultConfig() string {
	nodeRpc := m.GetExpectedNodeRpcSettings()
	esploraURL := EsploraURLForNetwork(m.bitcoinConf.Network)

	esploraLine := "# wallet-esplora-url="
	if esploraURL != "" {
		esploraLine = fmt.Sprintf("wallet-esplora-url=%s", esploraURL)
	}

	return fmt.Sprintf(`# bitwindow-enforcer-conf-version=2

# Enforcer Configuration - Generated by BitWindow
# These settings are converted to CLI arguments when the Enforcer starts.

# Enable wallet functionality (default: true)
enable-wallet=true

# Enable mempool support - required for getblocktemplate (default: true)
enable-mempool=true

# Node RPC settings (synced from Bitcoin Core config)
node-rpc-user=%s
node-rpc-pass=%s
node-rpc-addr=%s

# Node ZMQ sequence address (must match zmqpubsequence in bitcoin.conf)
node-zmq-addr-sequence=tcp://127.0.0.1:29000

# Network-specific esplora URL
%s
`, nodeRpc["node-rpc-user"], nodeRpc["node-rpc-pass"], nodeRpc["node-rpc-addr"], esploraLine)
}

// GetCliArgs converts current config settings to CLI arguments for the enforcer.
// Port of getCliArgs() from enforcer_conf_provider.dart.
func (m *EnforcerConfManager) GetCliArgs() []string {
	var args []string

	if m.Config == nil {
		return args
	}

	for key, value := range m.Config.Settings {
		switch value {
		case "true":
			args = append(args, fmt.Sprintf("--%s", key))
		case "false":
			continue
		default:
			if value != "" {
				args = append(args, fmt.Sprintf("--%s=%s", key, value))
			}
		}
	}

	// Add esplora URL if not in config
	if !m.Config.HasSetting("wallet-esplora-url") {
		esploraURL := EsploraURLForNetwork(m.bitcoinConf.Network)
		if esploraURL != "" {
			args = append(args, fmt.Sprintf("--wallet-esplora-url=%s", esploraURL))
		}
	}

	return args
}

// GetExpectedNodeRpcSettings derives RPC credentials from bitcoin config.
func (m *EnforcerConfManager) GetExpectedNodeRpcSettings() map[string]string {
	const host = "127.0.0.1"
	const defaultZmqSequence = "tcp://127.0.0.1:29000"

	port := m.bitcoinConf.GetRPCPort()

	if m.bitcoinConf.Config == nil {
		return map[string]string{
			"node-rpc-user":           "user",
			"node-rpc-pass":           "password",
			"node-rpc-addr":           fmt.Sprintf("%s:%d", host, port),
			"node-zmq-addr-sequence":  defaultZmqSequence,
		}
	}

	networkSection := CoreSectionForNetwork(m.bitcoinConf.Network)

	username := m.bitcoinConf.Config.GetEffectiveSetting("rpcuser", networkSection)
	if username == "" {
		username = "user"
	}

	password := m.bitcoinConf.Config.GetEffectiveSetting("rpcpassword", networkSection)
	if password == "" {
		password = "password"
	}

	zmqSequence := m.bitcoinConf.Config.GetEffectiveSetting("zmqpubsequence", networkSection)
	if zmqSequence == "" {
		zmqSequence = defaultZmqSequence
	}

	return map[string]string{
		"node-rpc-user":          username,
		"node-rpc-pass":          password,
		"node-rpc-addr":          fmt.Sprintf("%s:%d", host, port),
		"node-zmq-addr-sequence": zmqSequence,
	}
}

// SyncFromBitcoinConf syncs node-rpc settings from the bitcoin config.
func (m *EnforcerConfManager) SyncFromBitcoinConf() error {
	if m.Config == nil {
		return nil
	}

	expected := m.GetExpectedNodeRpcSettings()
	m.Config.SetSetting("node-rpc-user", expected["node-rpc-user"])
	m.Config.SetSetting("node-rpc-pass", expected["node-rpc-pass"])
	m.Config.SetSetting("node-rpc-addr", expected["node-rpc-addr"])
	m.Config.SetSetting("node-zmq-addr-sequence", expected["node-zmq-addr-sequence"])

	// Sync esplora URL
	esploraURL := EsploraURLForNetwork(m.bitcoinConf.Network)
	if esploraURL != "" {
		m.Config.SetSetting("wallet-esplora-url", esploraURL)
	} else {
		m.Config.RemoveSetting("wallet-esplora-url")
	}

	return m.SaveConfig()
}

// SaveConfig writes the current config to disk.
func (m *EnforcerConfManager) SaveConfig() error {
	if m.Config == nil {
		return nil
	}
	confPath := m.getConfigPath()
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(confPath, []byte(m.Config.Serialize()), 0644)
}

func (m *EnforcerConfManager) getConfigPath() string {
	return filepath.Join(enforcerRootDir(), bitwindowEnforcerConfFilename)
}

// enforcerRootDir returns the enforcer's root data directory.
func enforcerRootDir() string {
	home, _ := os.UserHomeDir()
	switch runtime.GOOS {
	case "darwin":
		return filepath.Join(home, "Library", "Application Support", "com.layertwolabs.enforcer")
	case "windows":
		return filepath.Join(home, "AppData", "Roaming", "LayerTwoLabs", "Enforcer")
	default: // linux
		return filepath.Join(home, ".local", "share", "com.layertwolabs.enforcer")
	}
}
