package config

import (
	"fmt"
	"strconv"
	"strings"
)

const enforcerConfVersionCommentPrefix = "# bitwindow-enforcer-conf-version="

// EnforcerConfig represents parsed enforcer configuration.
// Unlike Bitcoin Core, the enforcer doesn't read from a conf file directly -
// it only accepts CLI arguments. We store settings in a file and convert them
// to CLI args at launch time.
// 1:1 port of sail_ui/lib/models/enforcer_config.dart
type EnforcerConfig struct {
	Settings      map[string]string
	ConfigVersion int
}

func NewEnforcerConfig() *EnforcerConfig {
	return &EnforcerConfig{
		Settings:      make(map[string]string),
		ConfigVersion: 0,
	}
}

// ParseEnforcerConfig parses a simple key=value format config file (no sections).
func ParseEnforcerConfig(content string) *EnforcerConfig {
	config := NewEnforcerConfig()

	lines := strings.Split(content, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Parse version comment for migration system
		if strings.HasPrefix(trimmed, enforcerConfVersionCommentPrefix) {
			vStr := strings.TrimSpace(trimmed[len(enforcerConfVersionCommentPrefix):])
			if v, err := strconv.Atoi(vStr); err == nil && v >= 0 {
				config.ConfigVersion = v
			}
			continue
		}

		// Skip empty lines and other comments
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Parse key=value pairs
		eqIdx := strings.Index(trimmed, "=")
		if eqIdx > 0 {
			key := strings.TrimSpace(trimmed[:eqIdx])
			value := strings.TrimSpace(trimmed[eqIdx+1:])
			config.Settings[key] = value
		}
	}

	return config
}

// Serialize writes the config back to file format.
func (c *EnforcerConfig) Serialize() string {
	var b strings.Builder

	if c.ConfigVersion > 0 {
		fmt.Fprintf(&b, "%s%d\n\n", enforcerConfVersionCommentPrefix, c.ConfigVersion)
	}

	b.WriteString("# Enforcer Configuration - Generated by BitWindow\n")
	b.WriteString("# These settings are converted to CLI arguments when the Enforcer starts.\n\n")

	for key, value := range c.Settings {
		fmt.Fprintf(&b, "%s=%s\n", key, value)
	}

	return b.String()
}

func (c *EnforcerConfig) GetSetting(key string) string {
	return c.Settings[key]
}

func (c *EnforcerConfig) SetSetting(key, value string) {
	c.Settings[key] = value
}

func (c *EnforcerConfig) RemoveSetting(key string) {
	delete(c.Settings, key)
}

func (c *EnforcerConfig) HasSetting(key string) bool {
	_, ok := c.Settings[key]
	return ok
}
