package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/rs/zerolog"
)

// SidechainConfSpec defines how a sidechain's configuration should be managed.
type SidechainConfSpec struct {
	// Name is the sidechain name (e.g. "thunder", "bitassets").
	Name string
	// ConfigFilename is the config file name (e.g. "thunder.conf").
	ConfigFilename string
	// BasePort is the signet RPC port (e.g. 6009 for thunder).
	BasePort int
	// SkippedCliKeys are config keys that should not be converted to CLI args.
	SkippedCliKeys []string
	// PortStyle determines which config keys are used for network ports.
	// "grpc" = rpc-addr, net-addr, mainchain-grpc-url (thunder, zside, photon, etc.)
	// "zmq"  = rpc-port, net-addr, zmq-addr (bitassets, bitnames)
	PortStyle string
	// DirKey is the chains_config.json key for the data directory lookup.
	DirKey string
}

// SidechainConfManager manages a sidechain's key-value config file.
// Generic replacement for ThunderConfManager and ZSideConfManager.
type SidechainConfManager struct {
	Config     *GenericAppConfig
	ConfigPath string
	Spec       SidechainConfSpec

	bitcoinConf *BitcoinConfManager
	log         zerolog.Logger

	watcher   *fsnotify.Watcher
	watchDone chan struct{}
}

// NewSidechainConfManager creates a new conf manager for the given sidechain.
func NewSidechainConfManager(spec SidechainConfSpec, bitcoinConf *BitcoinConfManager, log zerolog.Logger) (*SidechainConfManager, error) {
	m := &SidechainConfManager{
		Spec:        spec,
		bitcoinConf: bitcoinConf,
		log:         log.With().Str("component", spec.Name+"-conf").Logger(),
	}
	if err := m.LoadConfig(); err != nil {
		return nil, fmt.Errorf("load %s config: %w", spec.Name, err)
	}
	if err := m.SyncNetworkFromBitcoinConf(); err != nil {
		m.log.Warn().Err(err).Msgf("failed to sync %s config from bitcoin conf", spec.Name)
	}
	return m, nil
}

// LoadConfig loads the config from file, or creates default if not exists.
func (m *SidechainConfManager) LoadConfig() error {
	m.ConfigPath = m.getConfigPath()

	data, err := os.ReadFile(m.ConfigPath)
	if err == nil {
		m.Config = ParseGenericAppConfig(string(data))
		return nil
	}

	if !os.IsNotExist(err) {
		return fmt.Errorf("read %s config: %w", m.Spec.Name, err)
	}

	content := m.GetDefaultConfig()
	m.Config = ParseGenericAppConfig(content)

	if mkErr := os.MkdirAll(filepath.Dir(m.ConfigPath), 0755); mkErr != nil {
		m.log.Error().Err(mkErr).Msgf("failed to create %s config directory", m.Spec.Name)
	} else if wErr := os.WriteFile(m.ConfigPath, []byte(content), 0644); wErr != nil {
		m.log.Error().Err(wErr).Str("path", m.ConfigPath).Msgf("failed to write default %s config", m.Spec.Name)
	} else {
		m.log.Info().Str("path", m.ConfigPath).Msgf("created default %s config file", m.Spec.Name)
	}

	return nil
}

// GetDefaultConfig generates the default config content.
func (m *SidechainConfManager) GetDefaultConfig() string {
	network := m.resolveNetwork()
	ports := m.getNetworkPorts(network)

	switch m.Spec.PortStyle {
	case "zmq":
		return fmt.Sprintf(`# %s Configuration - Generated by Orchestratord
# These settings are converted to CLI arguments when %s starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Log level for file output
log-level-file=WARN

# Network (signet or regtest)
network=%s

# RPC port
rpc-port=%s

# P2P networking address
net-addr=%s

# ZMQ notification address
zmq-addr=%s
`, m.Spec.Name, m.Spec.Name, network, ports["rpc-port"], ports["net-addr"], ports["zmq-addr"])

	default: // "grpc"
		return fmt.Sprintf(`# %s Configuration - Generated by Orchestratord
# These settings are converted to CLI arguments when %s starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Log level for file output
log-level-file=WARN

# Network (signet or regtest)
network=%s

# RPC server address
rpc-addr=%s

# P2P networking address
net-addr=%s

# Mainchain (Enforcer) gRPC connection URL
mainchain-grpc-url=%s
`, m.Spec.Name, m.Spec.Name, network, ports["rpc-addr"], ports["net-addr"], ports["mainchain-grpc-url"])
	}
}

// getNetworkPorts returns port mappings for the given network, derived from BasePort.
func (m *SidechainConfManager) getNetworkPorts(network string) map[string]string {
	base := m.Spec.BasePort
	var offset int
	switch network {
	case "regtest":
		offset = 10000
	case "mainnet":
		offset = 20000
	default: // signet
		offset = 0
	}

	rpcPort := base + offset
	netPort := base - 2000 + offset

	switch m.Spec.PortStyle {
	case "zmq":
		zmqPort := base + 22000 + offset
		return map[string]string{
			"rpc-port": fmt.Sprintf("%d", rpcPort),
			"net-addr": fmt.Sprintf("0.0.0.0:%d", netPort),
			"zmq-addr": fmt.Sprintf("127.0.0.1:%d", zmqPort),
		}
	default: // "grpc"
		return map[string]string{
			"rpc-addr":           fmt.Sprintf("127.0.0.1:%d", rpcPort),
			"net-addr":           fmt.Sprintf("0.0.0.0:%d", netPort),
			"mainchain-grpc-url": "http://localhost:50051",
		}
	}
}

// GetCliArgs converts current config to CLI args.
func (m *SidechainConfManager) GetCliArgs() []string {
	var args []string
	if m.Config == nil {
		return args
	}

	skipped := make(map[string]bool)
	for _, k := range m.Spec.SkippedCliKeys {
		skipped[k] = true
	}

	for key, value := range m.Config.Settings {
		if skipped[key] {
			continue
		}
		switch value {
		case "true":
			args = append(args, fmt.Sprintf("--%s", key))
		case "false":
			continue
		default:
			if value != "" {
				args = append(args, fmt.Sprintf("--%s=%s", key, value))
			}
		}
	}

	return args
}

// GetNetwork returns the current network from config.
func (m *SidechainConfManager) GetNetwork() string {
	if m.Config == nil {
		return "signet"
	}
	n := m.Config.GetSetting("network")
	if n == "" {
		return "signet"
	}
	return n
}

// WriteConfig writes raw config content to file.
func (m *SidechainConfManager) WriteConfig(content string) error {
	m.Config = ParseGenericAppConfig(content)

	confPath := m.getConfigPath()
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return fmt.Errorf("create dir: %w", err)
	}
	if err := os.WriteFile(confPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	m.log.Info().Str("path", confPath).Msgf("saved %s config", m.Spec.Name)
	return nil
}

// SyncNetworkFromBitcoinConf syncs network setting from Bitcoin config.
func (m *SidechainConfManager) SyncNetworkFromBitcoinConf() error {
	if m.Config == nil || m.bitcoinConf == nil {
		return nil
	}

	sidechainNetwork := m.resolveNetwork()
	currentNetwork := m.Config.GetSetting("network")
	if currentNetwork != sidechainNetwork {
		m.Config.SetSetting("network", sidechainNetwork)
		ports := m.getNetworkPorts(sidechainNetwork)
		for key, value := range ports {
			m.Config.SetSetting(key, value)
		}
		return m.saveConfig()
	}

	return nil
}

func (m *SidechainConfManager) resolveNetwork() string {
	if m.bitcoinConf == nil {
		return "signet"
	}
	switch m.bitcoinConf.Network {
	case NetworkRegtest:
		return "regtest"
	case NetworkForknet:
		return "mainnet"
	default:
		return "signet"
	}
}

func (m *SidechainConfManager) saveConfig() error {
	if m.Config == nil {
		return nil
	}
	confPath := m.getConfigPath()
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(confPath, []byte(m.Config.Serialize()), 0644); err != nil {
		return fmt.Errorf("save %s config: %w", m.Spec.Name, err)
	}
	m.log.Info().Str("path", confPath).Msgf("saved %s config", m.Spec.Name)
	return nil
}

func (m *SidechainConfManager) getConfigPath() string {
	dirs := MustDirConfig(m.Spec.DirKey)
	return filepath.Join(dirs.RootDir(), m.Spec.ConfigFilename)
}

// StartWatching watches the config directory for file changes.
func (m *SidechainConfManager) StartWatching() error {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		return fmt.Errorf("create watcher: %w", err)
	}

	confDir := filepath.Dir(m.getConfigPath())
	if err := os.MkdirAll(confDir, 0755); err != nil {
		_ = watcher.Close()
		return fmt.Errorf("create watch dir: %w", err)
	}

	if err := watcher.Add(confDir); err != nil {
		_ = watcher.Close()
		return fmt.Errorf("watch dir: %w", err)
	}

	m.watcher = watcher
	m.watchDone = make(chan struct{})

	go m.watchLoop()

	m.log.Debug().Str("dir", confDir).Msgf("%s config file watching enabled", m.Spec.Name)
	return nil
}

func (m *SidechainConfManager) StopWatching() {
	if m.watcher != nil {
		_ = m.watcher.Close()
	}
	if m.watchDone != nil {
		<-m.watchDone
	}
}

func (m *SidechainConfManager) watchLoop() {
	defer close(m.watchDone)

	var debounce *time.Timer
	var mu sync.Mutex

	for {
		select {
		case event, ok := <-m.watcher.Events:
			if !ok {
				return
			}
			if !strings.HasSuffix(event.Name, m.Spec.ConfigFilename) {
				continue
			}
			if event.Op&(fsnotify.Write|fsnotify.Create) == 0 {
				continue
			}

			mu.Lock()
			if debounce != nil {
				debounce.Stop()
			}
			debounce = time.AfterFunc(500*time.Millisecond, func() {
				m.reloadConfigFromFileSystem()
			})
			mu.Unlock()

		case err, ok := <-m.watcher.Errors:
			if !ok {
				return
			}
			m.log.Error().Err(err).Msgf("%s config watcher error", m.Spec.Name)
		}
	}
}

func (m *SidechainConfManager) reloadConfigFromFileSystem() {
	m.log.Info().Msgf("reloading %s config due to file system change", m.Spec.Name)

	confPath := m.getConfigPath()
	data, err := os.ReadFile(confPath)
	if err != nil {
		m.log.Error().Err(err).Msgf("failed to read %s config", m.Spec.Name)
		return
	}

	newConfig := ParseGenericAppConfig(string(data))
	if m.Config != nil && m.Config.Serialize() == newConfig.Serialize() {
		return
	}

	m.Config = newConfig
}

// KnownSidechainSpecs defines the configuration specs for all known sidechains.
var KnownSidechainSpecs = map[string]SidechainConfSpec{
	"thunder": {
		Name:           "Thunder",
		ConfigFilename: "thunder.conf",
		BasePort:       6009,
		SkippedCliKeys: []string{"network"},
		PortStyle:      "grpc",
		DirKey:         "thunder",
	},
	"bitassets": {
		Name:           "BitAssets",
		ConfigFilename: "bitassets.conf",
		BasePort:       6004,
		SkippedCliKeys: nil,
		PortStyle:      "zmq",
		DirKey:         "bitassets",
	},
	"bitnames": {
		Name:           "BitNames",
		ConfigFilename: "bitnames.conf",
		BasePort:       6002,
		SkippedCliKeys: nil,
		PortStyle:      "zmq",
		DirKey:         "bitnames",
	},
	"zside": {
		Name:           "ZSide",
		ConfigFilename: "zside.conf",
		BasePort:       6098,
		SkippedCliKeys: []string{"network"},
		PortStyle:      "grpc",
		DirKey:         "zside",
	},
	"photon": {
		Name:           "Photon",
		ConfigFilename: "photon.conf",
		BasePort:       6099,
		SkippedCliKeys: []string{"network"},
		PortStyle:      "grpc",
		DirKey:         "photon",
	},
	"truthcoin": {
		Name:           "Truthcoin",
		ConfigFilename: "truthcoin.conf",
		BasePort:       6013,
		SkippedCliKeys: []string{"network"},
		PortStyle:      "grpc",
		DirKey:         "truthcoin",
	},
	"coinshift": {
		Name:           "CoinShift",
		ConfigFilename: "coinshift.conf",
		BasePort:       6255,
		SkippedCliKeys: []string{"network"},
		PortStyle:      "grpc",
		DirKey:         "coinshift",
	},
}
