version: "3.9"
services:
  mainchain:
    image: barebitcoin/mainchain:latest
    volumes: [$HOME/.drivechain:/drivechain]
    healthcheck:
      # This doesn't verify that' we're able to query the JSON-RPC interface,
      # but merely that the container is listening on the RPC port.
      test: ["CMD", "curl", "http://localhost:18443"]
      interval: 1s
      start_interval: 20s
    ports: ["18443:18443"]
    command:
      - drivechaind
      - -printtoconsole
      - -regtest
      - -txindex
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0:18443
      - -rpcport=18443
      - -datadir=/drivechain

  testchain:
    image: barebitcoin/testchain:latest
    healthcheck:
      # This doesn't verify that' we're able to query the JSON-RPC interface,
      # but merely that the container is listening on the RPC port.
      test: ["CMD", "curl", "http://localhost:19000"]
      interval: 1s
      start_interval: 20s
    depends_on:
      mainchain:
        condition: service_healthy
    volumes: [$HOME/.testchain:/testchain]
    ports: ["19000:19000"]

    command:
      - testchaind
      - -printtoconsole
      - -slot=0
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0:19000
      - -rpcport=19000
      - -txindex
      - -regtest
      - -datadir=/testchain

  ethside:
    image: barebitcoin/ethside # TODO: change this once the image is pushed somewhere
    depends_on:
      mainchain:
        condition: service_healthy
    entrypoint: geth
    ports:
      - 8545:8545 # HTTP RPC
      - 8551:8551 # Authenticated RPC
    command:
      - --http # enable HTTP RPC
      # 'personal' API is needed for replicating the old ETH tutorial
      # made by Paul. Think it's some sort of wallet functionality? Not sure,
      # tbh. Went looking for a list of available APIs, without finding
      # anything.
      - --http.api=net,eth,personal,web3
      - --http.addr=0.0.0.0
      - --main.host=mainchain
      - --main.password=password
      - --main.user=user
      - --main.port=18443
