name: drivechain-faucet

services: 
  backend: 
    ports: [8082:8082]
    networks: [drivechain]

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/listclaims"]

    image: faucet-backend
    restart: unless-stopped
    build:
      context: ./faucet-backend
      platforms: [linux/amd64]

    command: 
      - faucet-backend
      - --bitcoincore.host=mainchain:38332
      - --bitcoincore.rpcuser=user
      - --bitcoincore.rpcpassword=password
      - --api.host=0.0.0.0:8082

networks:
  drivechain:
    name: drivechain-network          
    external: true
