build:
    go build -o ./bin/orchestratord ./cmd/orchestratord
    go build -o ./bin/orchestratorctl ./cmd/orchestratorctl

run *args:
    go run -v ./cmd/orchestratord {{args}}

test *args:
    go test -v ./... {{args}}

lint:
    go vet ./...

gen: gen-cusf
    buf generate --template buf.go.gen.yaml .

gen-cusf:
    buf generate --template buf.go.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

clean:
    rm -rf ./bin
    go clean
