build:
    go build -o ./bin/drivechaind ./cmd/drivechaind
    go build -o ./bin/drivechain-cli ./cmd/drivechain-cli

run *args:
    go run -v ./cmd/drivechaind {{args}}

test *args:
    go test -v ./... {{args}}

lint:
    go vet ./...

gen: gen-cusf
    buf generate --template buf.go.gen.yaml .

# The enforcer holds the cusf protos it serves. cusf_sidechain_proto is stale,
# and a generation from it deletes every method the enforcer added since.
gen-cusf:
    buf generate --template buf.go.gen.yaml --exclude-path proto/cusf/mainchain/v1/wallet.proto https://github.com/LayerTwo-Labs/bip300301_enforcer.git

clean:
    rm -rf ./bin
    go clean
