/// Configuration model for the BitNames sidechain.
/// BitNames doesn't read from a conf file directly - it only accepts CLI arguments.
/// We store settings in a file and convert them to CLI args at launch time.
class BitnamesConfig {
  Map<String, String> settings = {};

  BitnamesConfig();

  BitnamesConfig.fromConfig(BitnamesConfig other) {
    settings = Map<String, String>.from(other.settings);
  }

  /// Parse a simple key=value format config file (no sections)
  static BitnamesConfig parse(String content) {
    final config = BitnamesConfig();
    final lines = content.split('\n');

    for (final line in lines) {
      final trimmed = line.trim();

      // Skip empty lines and comments
      if (trimmed.isEmpty || trimmed.startsWith('#')) {
        continue;
      }

      // Parse key=value pairs
      final equals = trimmed.indexOf('=');
      if (equals > 0) {
        final key = trimmed.substring(0, equals).trim();
        final value = trimmed.substring(equals + 1).trim();
        config.settings[key] = value;
      }
    }

    return config;
  }

  String serialize() {
    final buffer = StringBuffer();

    buffer.writeln('# BitNames Configuration - Generated by BitNames App');
    buffer.writeln('# These settings are converted to CLI arguments when BitNames starts.');
    buffer.writeln();

    for (final entry in settings.entries) {
      buffer.writeln('${entry.key}=${entry.value}');
    }

    return buffer.toString();
  }

  void setSetting(String key, String value) {
    settings[key] = value;
  }

  void removeSetting(String key) {
    settings.remove(key);
  }

  String? getSetting(String key) {
    return settings[key];
  }

  bool hasSetting(String key) {
    return settings.containsKey(key);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! BitnamesConfig) return false;

    if (settings.length != other.settings.length) return false;
    for (final key in settings.keys) {
      if (settings[key] != other.settings[key]) return false;
    }

    return true;
  }

  @override
  int get hashCode {
    return settings.hashCode;
  }
}
