import 'package:get_it/get_it.dart';
import 'package:sail_ui/sail_ui.dart';

/// Provider for Truthcoin configuration settings.
class TruthcoinConfProvider extends GenericSidechainConfProvider {
  TruthcoinConfProvider._create();

  static Future<TruthcoinConfProvider> create() async {
    final instance = TruthcoinConfProvider._create();
    await instance.initialize();
    return instance;
  }

  @override
  String get appName => 'Truthcoin';

  @override
  String get configFileName => 'truthcoin.conf';

  @override
  String getDataDir() => Truthcoin().datadir();

  @override
  List<String> get skippedCliKeys => ['network'];

  @override
  Map<String, String> getNetworkPorts(String network) {
    switch (network) {
      case 'regtest':
        return {
          'rpc-addr': '127.0.0.1:16013',
          'net-addr': '0.0.0.0:14013',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'mainnet':
        return {
          'rpc-addr': '127.0.0.1:26013',
          'net-addr': '0.0.0.0:24013',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'signet':
      default:
        return {
          'rpc-addr': '127.0.0.1:6013',
          'net-addr': '0.0.0.0:4013',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
    }
  }

  @override
  String getDefaultConfig() {
    String network = 'signet';
    try {
      final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
      network = switch (bitcoinConfProvider.network) {
        BitcoinNetwork.BITCOIN_NETWORK_SIGNET => 'signet',
        BitcoinNetwork.BITCOIN_NETWORK_REGTEST => 'regtest',
        BitcoinNetwork.BITCOIN_NETWORK_FORKNET => 'mainnet',
        _ => 'signet',
      };
    } catch (_) {}

    final ports = getNetworkPorts(network);

    return '''# Truthcoin Configuration - Generated by Truthcoin App
# These settings are converted to CLI arguments when Truthcoin starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Log level for file output
log-level-file=WARN

# Network (signet or regtest)
network=$network

# RPC server address
rpc-addr=${ports['rpc-addr']}

# P2P networking address
net-addr=${ports['net-addr']}

# Mainchain (Enforcer) gRPC connection URL
mainchain-grpc-url=${ports['mainchain-grpc-url']}
''';
  }
}
