fix:
    dart fix --apply

lint: fix

gen-version:
    cd ../ && bash scripts/generate-version.sh thunder

run:
    #!/usr/bin/env bash
    case "$(uname -s)" in
        Darwin*)  flutter run -d macos;;    # macOS
        Linux*)   flutter run -d linux;;    # Linux
        MINGW*|MSYS*|CYGWIN*)  flutter run -d windows;; # Windows
        *)        echo "Unknown operating system" && exit 1 ;;
    esac
