name: thunder
description: UI for Drivechain (BIP300/301) based sidechains
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.13.9

dependencies:
  flutter:
    sdk: flutter
  sail_ui:
    path: ../sail_ui
  sentry_flutter: ^9.0.0

  cupertino_icons: ^1.0.8
  dart_coin_rpc:
    git:
      url: https://github.com/barebitcoin/dart_coin_rpc.git
      # master, as of 08.06.2024
      ref: ab0b7cb2de6e1634a6e65892770ed0d157d38443
  flutter_highlighter: ^0.1.1
  logger: ^2.6.0
  dio: 5.7.0
  auto_route: ^10.1.0
  get_it: ^7.7.0
  qr_flutter: ^4.1.0
  window_manager: ^0.5.0
  collection: ^1.18.0
  stacked: ^3.4.3
  desktop_multi_window: ^0.2.1
  synchronized: ^3.3.1
  intl: ^0.20.2
  http: ^1.3.0
  path_provider: ^2.1.5
  crypto: ^3.0.5
  connectrpc: 0.4.0
  path: ^1.9.1

# Needed for silencing complaints from adding the web3dart lib
dependency_overrides:
  stream_channel: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sentry_dart_plugin: ^2.4.1

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.0
  msix: ^3.16.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/thunder.png"
    icon_size: 256
  macos:
    generate: true
  image_path: "assets/thunder.png"


flutter:
  uses-material-design: true

  assets:
    - assets/bin/

  fonts:
    - family: Inter
      fonts:
        - asset: ./assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: ./assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: ./assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: ./assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: ./assets/fonts/Inter-Black.ttf
          weight: 700

    - family: SourceCodePro
      fonts:
        - asset: ./assets/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: ./assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: ./assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: ./assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/SourceCodePro-Bold.ttf
          weight: 600
        - asset: ./assets/fonts/SourceCodePro-Black.ttf
          weight: 700

        - asset: ./assets/fonts/SourceCodePro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: ./assets/fonts/SourceCodePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: ./assets/fonts/SourceCodePro-Italic.ttf
          style: italic
          weight: 400
        - asset: ./assets/fonts/SourceCodePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: ./assets/fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 600
        - asset: ./assets/fonts/SourceCodePro-BlackItalic.ttf
          style: italic
          weight: 600

# Windows release stuff.
# This currently relies on having a self-signed certificate
# locally available, which must be changed before this is
# properly deployed (either published to the MS store or 
# as an installer on a website somewhere).
# https://pub.dev/packages/msix
msix_config:
  display_name: Thunder
  languages: en-us
  windows_build_args: --dart-define-from-file=build-vars.env
  publisher_display_name: LayerTwo Labs
  identity_name: com.layertwolabs.thunder
  msix_version: 1.0.0.0
  logo_path: logo.png
  capabilities: internetClientServer
  output_name: Thunder
  store_certificate: false  # Use a test certificate instead of store certificate
  install_certificate: false # Don't install certificate during CI builds
  os_min_version: 10.0.17763.0
  store: false  # Not publishing to Microsoft Store

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: thunder
