name: faucet
description: "a drivechain faucet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # internal packages
  sail_ui:
    path: ../sail_ui

  cupertino_icons: ^1.0.8
  stacked: ^3.4.2
  get_it: ^7.7.0
  logger: ^2.3.0
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
