package testharness

import (
	"bufio"
	"context"
	"crypto/rand"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"
	"time"

	"connectrpc.com/connect"
	rpc "github.com/LayerTwo-Labs/sidesail/sidechain-orchestrator/gen/walletmanager/v1/walletmanagerv1connect"
	"github.com/LayerTwo-Labs/sidesail/sidechain-orchestrator/wallet"
	"github.com/rs/zerolog"
)

// Node represents a single test node: bitcoind + orchestratord (real subprocess) + gRPC client.
type Node struct {
	Name            string
	Datadir         string // root temp dir for this node
	BitwindowDir    string // bitwindow-dir for orchestratord
	BitcoindProcess *os.Process
	OrchdProcess    *os.Process
	BitcoindRPCPort int
	BitcoindP2PPort int
	OrchdGRPCPort   int

	// Direct Core RPC for mining helpers (not via orchestrator).
	CoreRPC *wallet.CoreRPCClient

	// gRPC client to this node's orchestratord WalletManagerService.
	WalletClient rpc.WalletManagerServiceClient

	log       zerolog.Logger
	closeOnce sync.Once
}

// testPorts returns ports for a test run. A single random base is chosen per
// harness (via randomPortBase), then each node gets a 300-wide band:
//   node0: base, base+100, base+200
//   node1: base+300, base+400, base+500
//   ...
// This avoids the previous bug where each call generated independent random
// bases that could collide.
func testPorts(base, nodeIndex int) (rpcPort, p2pPort, grpcPort int) {
	nodeBase := base + nodeIndex*300
	return nodeBase, nodeBase + 100, nodeBase + 200
}

// randomPortBase picks a random base port in 40000-59000 range.
func randomPortBase() int {
	b := make([]byte, 2)
	_, _ = rand.Read(b)
	return 40000 + int(b[0])%190*100
}

// newNode creates and starts a fully-wired Node with real subprocesses.
// Ports must be pre-allocated by the caller (harness allocates all upfront).
func newNode(
	t *testing.T,
	name, rootDir, bitcoindBin, orchBin string,
	rpcPort, p2pPort, grpcPort int,
	log zerolog.Logger,
) *Node {
	t.Helper()

	nlog := log.With().Str("node", name).Logger()

	nodeDir := filepath.Join(rootDir, name)
	bitwindowDir := filepath.Join(nodeDir, "bitwindow")
	bitcoinDataDir := filepath.Join(nodeDir, "bitcoin")

	for _, d := range []string{bitwindowDir, bitcoinDataDir} {
		if err := os.MkdirAll(d, 0700); err != nil {
			t.Fatalf("testharness[%s]: mkdir %s: %v", name, d, err)
		}
	}

	n := &Node{
		Name:            name,
		Datadir:         nodeDir,
		BitwindowDir:    bitwindowDir,
		BitcoindRPCPort: rpcPort,
		BitcoindP2PPort: p2pPort,
		OrchdGRPCPort:   grpcPort,
		log:             nlog,
	}

	// 1. Write bitcoin.conf for bitcoind.
	bitcoinConf := fmt.Sprintf(`regtest=1
server=1
rpcuser=test
rpcpassword=test
txindex=1
fallbackfee=0.00001
[regtest]
rpcport=%d
port=%d
`, rpcPort, p2pPort)

	if err := os.WriteFile(filepath.Join(bitcoinDataDir, "bitcoin.conf"), []byte(bitcoinConf), 0600); err != nil {
		t.Fatalf("testharness[%s]: write bitcoin.conf: %v", name, err)
	}

	// 2. Write bitwindow-bitcoin.conf so orchestratord can find Core RPC.
	bitwindowBitcoinConf := fmt.Sprintf(`# Generated by test harness
regtest=1
server=1
rpcuser=test
rpcpassword=test
datadir=%s
[regtest]
rpcport=%d
port=%d
`, bitcoinDataDir, rpcPort, p2pPort)

	if err := os.WriteFile(filepath.Join(bitwindowDir, "bitwindow-bitcoin.conf"), []byte(bitwindowBitcoinConf), 0600); err != nil {
		t.Fatalf("testharness[%s]: write bitwindow-bitcoin.conf: %v", name, err)
	}

	// 3. Start bitcoind.
	bitcoindCmd := exec.Command(bitcoindBin, "-regtest", fmt.Sprintf("-datadir=%s", bitcoinDataDir), "-daemon=0", "-printtoconsole=0")
	bitcoindCmd.Stdout = nil
	bitcoindCmd.Stderr = nil
	if err := bitcoindCmd.Start(); err != nil {
		t.Fatalf("testharness[%s]: start bitcoind: %v", name, err)
	}
	n.BitcoindProcess = bitcoindCmd.Process
	nlog.Info().Int("pid", bitcoindCmd.Process.Pid).Int("rpc", rpcPort).Int("p2p", p2pPort).Msg("bitcoind started")

	t.Cleanup(func() {
		if n.BitcoindProcess != nil {
			stopProcess(n.BitcoindProcess)
		}
	})
	go func() { _ = bitcoindCmd.Wait() }()

	// 4. Wait for bitcoind RPC to be ready.
	n.CoreRPC = wallet.NewCoreRPCClient("127.0.0.1", rpcPort, "test", "test")
	waitForBitcoind(t, n.CoreRPC, name)

	// 5. Start orchestratord as a real subprocess.
	orchCmd := exec.Command(orchBin,
		"--datadir", bitwindowDir,
		"--bitwindow-dir", bitwindowDir,
		"--network", "regtest",
		"--rpclisten", fmt.Sprintf("127.0.0.1:%d", grpcPort),
		"--loglevel", "info",
	)
	// Pipe both stdout and stderr for debugging.
	orchStdout, err := orchCmd.StdoutPipe()
	if err != nil {
		t.Fatalf("testharness[%s]: orchd stdout pipe: %v", name, err)
	}
	orchStderr, err := orchCmd.StderrPipe()
	if err != nil {
		t.Fatalf("testharness[%s]: orchd stderr pipe: %v", name, err)
	}

	if err := orchCmd.Start(); err != nil {
		t.Fatalf("testharness[%s]: start orchestratord: %v", name, err)
	}
	n.OrchdProcess = orchCmd.Process
	nlog.Info().Int("pid", orchCmd.Process.Pid).Int("grpc", grpcPort).Msg("orchestratord started")

	t.Cleanup(func() {
		if n.OrchdProcess != nil {
			stopProcess(n.OrchdProcess)
		}
	})

	// Watch orchestratord stdout for "serving gRPC" to know it's ready.
	orchReady := make(chan struct{})
	go func() {
		scanner := bufio.NewScanner(orchStdout)
		for scanner.Scan() {
			line := scanner.Text()
			nlog.Info().Str("src", "orchd").Msg(line)
			if strings.Contains(line, "serving gRPC") {
				close(orchReady)
			}
		}
	}()
	go func() {
		scanner := bufio.NewScanner(orchStderr)
		for scanner.Scan() {
			nlog.Info().Str("src", "orchd-err").Msg(scanner.Text())
		}
	}()
	go func() { _ = orchCmd.Wait() }()

	// 6. Wait for orchestratord to be ready.
	select {
	case <-orchReady:
		nlog.Info().Msg("orchestratord serving")
	case <-time.After(15 * time.Second):
		t.Fatalf("testharness[%s]: orchestratord did not start serving within 15s", name)
	}

	// 7. Create ConnectRPC client — same pattern as orchestratorctl CLI.
	// Uses connect.WithGRPC() which triggers h2c upgrade via the server's
	// h2c.NewHandler. This works over HTTP/1.1.
	n.WalletClient = rpc.NewWalletManagerServiceClient(
		http.DefaultClient,
		fmt.Sprintf("http://127.0.0.1:%d", grpcPort),
		connect.WithGRPC(),
	)

	nlog.Info().Msg("node ready")
	return n
}

// close shuts down orchestratord and bitcoind.
func (n *Node) close() {
	n.closeOnce.Do(func() {
		if n.OrchdProcess != nil {
			stopProcess(n.OrchdProcess)
			n.OrchdProcess = nil
		}
		if n.BitcoindProcess != nil {
			stopProcess(n.BitcoindProcess)
			n.BitcoindProcess = nil
		}
	})
}

// waitForBitcoind polls getblockchaininfo until the node responds or times out.
func waitForBitcoind(t *testing.T, rpcClient *wallet.CoreRPCClient, nodeName string) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	for {
		select {
		case <-ctx.Done():
			t.Fatalf("testharness[%s]: bitcoind did not become ready within 30s", nodeName)
		default:
		}
		if result, err := rpcClient.GetBlockchainInfo(ctx); err == nil && result != nil {
			return
		}
		time.Sleep(250 * time.Millisecond)
	}
}


// GenerateToAddress mines blocks to the given address using the raw RPC client.
func (n *Node) GenerateToAddress(ctx context.Context, blocks int, addr string) ([]string, error) {
	return n.CoreRPC.GenerateToAddress(ctx, blocks, addr)
}

// orchBinaryName returns "orchestratord" with .exe on Windows.
func orchBinaryName() string {
	name := "orchestratord"
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	return name
}
