import 'package:get_it/get_it.dart';
import 'package:sail_ui/sail_ui.dart';

/// Provider for BitAssets configuration settings.
class BitassetsConfProvider extends GenericSidechainConfProvider {
  BitassetsConfProvider._create();

  static Future<BitassetsConfProvider> create() async {
    final instance = BitassetsConfProvider._create();
    await instance.initialize();
    return instance;
  }

  @override
  String get appName => 'BitAssets';

  @override
  String get configFileName => 'bitassets.conf';

  @override
  String getDataDir() => BitAssets().datadir();

  @override
  Map<String, String> getNetworkPorts(String network) {
    switch (network) {
      case 'regtest':
        return {
          'rpc-host': '127.0.0.1',
          'rpc-port': '16004',
          'net-addr': '0.0.0.0:14004',
          'zmq-addr': '127.0.0.1:38004',
          'mainchain-grpc-port': '50051',
        };
      case 'signet':
      default:
        return {
          'rpc-host': '127.0.0.1',
          'rpc-port': '6004',
          'net-addr': '0.0.0.0:4004',
          'zmq-addr': '127.0.0.1:28004',
          'mainchain-grpc-port': '50051',
        };
    }
  }

  @override
  String getDefaultConfig() {
    String network = 'signet';
    try {
      final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
      network = switch (bitcoinConfProvider.network) {
        BitcoinNetwork.BITCOIN_NETWORK_SIGNET => 'signet',
        BitcoinNetwork.BITCOIN_NETWORK_REGTEST => 'regtest',
        _ => 'signet',
      };
    } catch (_) {}

    final ports = getNetworkPorts(network);

    return '''# BitAssets Configuration - Generated by BitAssets App
# These settings are converted to CLI arguments when BitAssets starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Network (signet or regtest)
network=$network

# RPC server address
rpc-host=${ports['rpc-host']}
rpc-port=${ports['rpc-port']}

# P2P networking address
net-addr=${ports['net-addr']}

# ZMQ pub/sub address
zmq-addr=${ports['zmq-addr']}

# Mainchain (Enforcer) gRPC connection
mainchain-grpc-host=127.0.0.1
mainchain-grpc-port=${ports['mainchain-grpc-port']}
''';
  }
}
