gen: gen-validator
    buf generate --template buf.web.gen.yaml server
    buf generate --template buf.web.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git
    cd server && buf generate --template buf.go.gen.yaml .

gen-validator:
    cd server && buf generate --template buf.go.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

build-client:
    bun run build

build-docker:
    docker build --platform linux/amd64 --file Dockerfile .

run-client: 
    bun dev 

run-client-prod: 
    env NEXT_PUBLIC_API_BASE_URL=https://node.drivechain.info/api \
        API_BASE_URL=https://node.drivechain.info/api \
        bun dev

run:
    #!/usr/bin/env bash
    # Run server in background
    ./server/faucetd &
    SERVER_PID=$!
    
    # Wait for server to start
    sleep 3
    
    # Run client
    bun dev
    
    # Clean up server when client exits
    kill $SERVER_PID

lint: 
    golangci-lint run ./server/...

run-server: build-server
    ./server/faucetd

build-server:
    cd server && go build -o faucetd
