format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

gen: gen-validator
    buf generate --template ../buf.dart.gen.yaml ./server
    cd server && buf generate --template buf.go.gen.yaml .

gen-validator:
    cd server && buf generate --template buf.go.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

build-client:
    flutter build web

run-client: 
    # specify port 3000 for CORS to work properly against the remote server
    # specify base URL for local development
    flutter run -d chrome --web-port 3000 --dart-define=FAUCET_BASE_URL=http://localhost:8082

run-client-prod: 
    # specify port 3000 for CORS to work properly against the remote server
    # specify base URL for local development
    flutter run -d chrome --web-port 3000 --dart-define=FAUCET_BASE_URL=https://node.drivechain.info/api

run-server: build-server
    ./server/faucetd

build-server:
    cd server && go build -o faucetd

lint: 
    golangci-lint run ./server/...

run:
    #!/usr/bin/env bash
    # Run server in background
    ./server/faucetd &
    SERVER_PID=$!
    
    # Wait for server to start
    sleep 3
    
    # Run client
    flutter run -d chrome --web-port 3000 --dart-define=FAUCET_BASE_URL=http://localhost:8082
    
    # Clean up server when client exits
    kill $SERVER_PID
