format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

gen:
    buf generate ../../servers/faucet 

build:
    flutter build web

run: 
    # specify port 3000 for CORS to work properly against the remote server
    # specify base URL for local development
    flutter run -d chrome --web-port 3000 --dart-define=FAUCET_BASE_URL=http://localhost:8082

run-prod: 
    # specify port 3000 for CORS to work properly against the remote server
    # specify base URL for local development
    flutter run -d chrome --web-port 3000 --dart-define=FAUCET_BASE_URL=https://node.drivechain.info/api
