# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: CB6BF331-C832-4005-970F-B880295700CA
publisher: LayerTwo Labs
publisher_url: https://github.com/LayerTwo-Labs/drivechain-frontends
display_name: BitNames
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
