import 'dart:async';
import 'dart:io' show Directory, File, FileSystemEvent, Platform;

import 'package:flutter/foundation.dart';
import 'package:get_it/get_it.dart';
import 'package:logger/logger.dart';
import 'package:path/path.dart' as path;
import 'package:sail_ui/sail_ui.dart';

/// Provider for Enforcer configuration settings.
/// Unlike Bitcoin Core, the Enforcer doesn't read from a conf file directly -
/// it only accepts CLI arguments. We store settings in a file and convert them
/// to CLI args at launch time.
class EnforcerConfProvider extends ChangeNotifier {
  final Logger log = GetIt.I.get<Logger>();

  // File watching and management
  StreamSubscription<FileSystemEvent>? _fileWatcher;
  Timer? _fileWatchDebouncer;

  // Config state
  EnforcerConfig? _currentConfig;
  String? _currentConfigPath;

  // Getters
  EnforcerConfig? get currentConfig => _currentConfig;
  String? get currentConfigPath => _currentConfigPath;

  // Private constructor
  EnforcerConfProvider._create();

  // Async factory
  static Future<EnforcerConfProvider> create() async {
    final instance = EnforcerConfProvider._create();
    await instance.loadConfig();
    instance._listenToBitcoinConf();
    return instance;
  }

  void _listenToBitcoinConf() {
    if (GetIt.I.isRegistered<BitcoinConfProvider>()) {
      GetIt.I.get<BitcoinConfProvider>().addListener(_onBitcoinConfChanged);
      _syncNodeRpcSettings();
    }
  }

  void _onBitcoinConfChanged() {
    _syncNodeRpcSettings();
    notifyListeners();
  }

  /// Sync node-rpc-* settings from BitcoinConfProvider into _currentConfig
  void _syncNodeRpcSettings() {
    if (_currentConfig == null) return;

    if (!GetIt.I.isRegistered<BitcoinConfProvider>()) {
      _currentConfig!.setSetting('node-rpc-user', 'user');
      _currentConfig!.setSetting('node-rpc-pass', 'password');
      _currentConfig!.setSetting('node-rpc-addr', 'localhost:38332');
      return;
    }

    final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
    if (bitcoinConfProvider.currentConfig == null) {
      _currentConfig!.setSetting('node-rpc-user', 'user');
      _currentConfig!.setSetting('node-rpc-pass', 'password');
      _currentConfig!.setSetting('node-rpc-addr', 'localhost:38332');
      return;
    }

    final config = bitcoinConfProvider.currentConfig!;
    final networkSection = bitcoinConfProvider.network.toCoreNetwork();

    final username = config.getEffectiveSetting('rpcuser', networkSection) ?? 'user';
    final password = config.getEffectiveSetting('rpcpassword', networkSection) ?? 'password';
    final port = bitcoinConfProvider.rpcPort;

    // Use 0.0.0.0 on non-Windows for localhost binding
    final host = Platform.isWindows ? 'localhost' : '0.0.0.0';

    _currentConfig!.setSetting('node-rpc-user', username);
    _currentConfig!.setSetting('node-rpc-pass', password);
    _currentConfig!.setSetting('node-rpc-addr', '$host:$port');
  }

  @override
  void dispose() {
    _fileWatcher?.cancel();
    _fileWatchDebouncer?.cancel();
    if (GetIt.I.isRegistered<BitcoinConfProvider>()) {
      GetIt.I.get<BitcoinConfProvider>().removeListener(_onBitcoinConfChanged);
    }
    super.dispose();
  }

  /// Get the path to the enforcer config file
  String _getConfigPath() {
    final datadir = BitWindow().datadir();
    return path.join(datadir, 'bitwindow-enforcer.conf');
  }

  Future<void> loadConfig() async {
    try {
      _currentConfigPath = _getConfigPath();
      final file = File(_currentConfigPath!);

      String content = '';
      if (await file.exists()) {
        content = await file.readAsString();
      } else {
        // Use the default config if no file exists
        content = getDefaultConfig();

        // Write default config to disk
        try {
          await file.parent.create(recursive: true);
          await file.writeAsString(content);
          log.i('Created default enforcer config file: ${file.path}');
        } catch (e) {
          log.e('Failed to write default enforcer config file: $e');
        }
      }

      // Parse config
      _currentConfig = EnforcerConfig.parse(content);

      // Set up file watching
      _setupFileWatching();

      notifyListeners();
    } catch (e) {
      log.e('Failed to load enforcer config: $e');
    }
  }

  /// Get the default configuration content
  String getDefaultConfig() {
    return '''# Enforcer Configuration - Generated by BitWindow
# These settings are converted to CLI arguments when the Enforcer starts.

# Enable wallet functionality (default: true)
enable-wallet=true

# Enable mempool support - required for getblocktemplate (default: true)
enable-mempool=true

# Network-specific esplora URL (auto-detected if not set)
# Uncomment and set to override the default for your network
# wallet-esplora-url=https://mempool.space/api
''';
  }

  /// Get the current configuration content as string
  String getCurrentConfigContent() {
    if (_currentConfig == null) {
      return getDefaultConfig();
    }
    return _currentConfig!.serialize();
  }

  /// Write configuration content to the file
  Future<void> writeConfig(String content) async {
    try {
      final config = EnforcerConfig.parse(content);
      _currentConfig = config;

      final confPath = _getConfigPath();
      final file = File(confPath);
      await file.parent.create(recursive: true);
      await file.writeAsString(content);

      log.i('Saved enforcer config to $confPath');
      notifyListeners();
    } catch (e) {
      log.e('Failed to write enforcer config: $e');
      rethrow;
    }
  }

  /// Get network-specific esplora URL
  String? getEsploraUrlForNetwork(BitcoinNetwork network) {
    switch (network) {
      case BitcoinNetwork.BITCOIN_NETWORK_REGTEST:
        return 'http://localhost:3002';

      case BitcoinNetwork.BITCOIN_NETWORK_TESTNET:
        // Testnet not supported for enforcer
        return null;

      case BitcoinNetwork.BITCOIN_NETWORK_MAINNET:
      case BitcoinNetwork.BITCOIN_NETWORK_FORKNET:
        return 'https://mempool.space/api';

      case BitcoinNetwork.BITCOIN_NETWORK_SIGNET:
      default:
        // Signet uses the enforcer's built-in default
        return null;
    }
  }

  /// Convert current config to CLI args for the enforcer
  List<String> getCliArgs(BitcoinNetwork network) {
    final args = <String>[];

    if (_currentConfig == null) return args;

    for (final entry in _currentConfig!.settings.entries) {
      final key = entry.key;
      final value = entry.value;

      if (value == 'true') {
        // Boolean flag set to true
        args.add('--$key');
      } else if (value == 'false') {
        // Boolean flag set to false - don't add
        continue;
      } else if (value.isNotEmpty) {
        // Key=value setting
        args.add('--$key=$value');
      }
    }

    // Add network-specific esplora URL default if not in config
    if (!_currentConfig!.hasSetting('wallet-esplora-url')) {
      final esploraUrl = getEsploraUrlForNetwork(network);
      if (esploraUrl != null && esploraUrl.isNotEmpty) {
        args.add('--wallet-esplora-url=$esploraUrl');
      }
    }

    return args;
  }

  void _setupFileWatching() {
    // Cancel existing watcher
    _fileWatcher?.cancel();

    try {
      final confPath = _getConfigPath();
      final confDir = Directory(path.dirname(confPath));

      if (!confDir.existsSync()) {
        confDir.createSync(recursive: true);
      }

      // Watch the directory for config file changes
      _fileWatcher = confDir
          .watch(events: FileSystemEvent.modify | FileSystemEvent.create | FileSystemEvent.delete)
          .where((event) => event.path.endsWith('bitwindow-enforcer.conf'))
          .listen(_handleFileSystemEvent);

      log.d('Enforcer config file watching enabled for ${confDir.path}');
    } catch (e) {
      log.e('Failed to setup enforcer config file watching: $e');
    }
  }

  void _handleFileSystemEvent(FileSystemEvent event) {
    log.d('Enforcer config file changed: ${event.path}');

    // Debounce file changes to avoid rapid reloads
    _fileWatchDebouncer?.cancel();
    _fileWatchDebouncer = Timer(const Duration(milliseconds: 500), () {
      _reloadConfigFromFileSystem();
    });
  }

  void _reloadConfigFromFileSystem() async {
    try {
      log.i('Reloading enforcer config due to file system change');

      final confPath = _getConfigPath();
      final file = File(confPath);

      if (await file.exists()) {
        final content = await file.readAsString();
        final newConfig = EnforcerConfig.parse(content);

        // Update config if content actually changed
        if (newConfig != _currentConfig) {
          _currentConfig = newConfig;
          _syncNodeRpcSettings();
          notifyListeners();
        }
      }
    } catch (e) {
      log.e('Failed to reload enforcer config from file system: $e');
    }
  }
}
