fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format

lint: format fix

gen-version:
    cd ../ && bash scripts/generate-version.sh bitnames

run:
    #!/usr/bin/env bash
    case "$(uname -s)" in
        Darwin*)  flutter run -d macos;;    # macOS
        Linux*)   flutter run -d linux;;    # Linux
        MINGW*|MSYS*|CYGWIN*)  flutter run -d windows;; # Windows
        *)        echo "Unknown operating system" && exit 1 ;;
    esac
