fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

lint: format fix

gen-server:
    cd server && buf generate --template buf.go.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git
    cd server && buf generate --template buf.go.gen.yaml .

gen: gen-server gen-bitwindow-client

gen-version:
    cd ../ && bash scripts/generate-version.sh bitwindow

gen-bitwindow-client:
    cd ../sail_ui && just gen

clean:
    rm assets/bin/*

download:
    bash scripts/download-binaries.sh

run: download
    #!/usr/bin/env bash
    case "$(uname -s)" in
        Darwin*)  flutter run -d macos;;    # macOS
        Linux*)   flutter run -d linux;;    # Linux
        MINGW*|MSYS*|CYGWIN*)  flutter run -d windows;; # Windows
        *)        echo "Unknown operating system" && exit 1 ;;
    esac
