fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

lint: format fix

gen-server:
    cd server && buf generate --template buf.go.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git
    cd server && buf generate --template buf.go.gen.yaml .

gen: gen-server gen-bitwindow-client

gen-bitwindow-client:
    cd ../sail_ui && just gen

clean:
    rm assets/bin/*

download:
    bash scripts/download-binaries.sh macos

run: download
    flutter run -d macos
