fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format

analyze:
    dart analyze
    dart run custom_lint

lint: format fix analyze

gen-version:
    cd ../ && bash scripts/generate-version.sh sail_ui

gen-enforcer:
    buf generate --template ../buf.dart.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

gen: gen-enforcer
    buf generate --template ../buf.dart.gen.yaml ../bitwindow/server
    buf generate --template ../buf.dart.gen.yaml ../truthcoin/server
    buf generate --template ../buf.dart.gen.yaml https://github.com/barebitcoin/btc-buf.git