format:
   find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format

gen-version:
    cd ../ && bash scripts/generate-version.sh sail_ui

gen-enforcer:
    buf generate --template ../buf.dart.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

gen: gen-enforcer
    buf generate --template ../buf.dart.gen.yaml ../bitwindow/server