name: launcher
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.3.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  path_provider: ^2.0.15
  hex: ^0.2.0
  get_it: ^7.6.4
  logger: ^2.0.2+1
  provider: ^6.0.5
  sail_ui:
    path: ../sail_ui
  shared_preferences: ^2.2.2
  window_manager: ^0.3.7
  crypto: ^3.0.3
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/chain_config.json
