fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format

analyze:
    dart analyze

lint: format fix analyze

gen-enforcer:
    buf generate --template ../buf.dart.gen.yaml --exclude-path proto/cusf/mainchain/v1/wallet.proto https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git

gen: gen-enforcer
    buf generate --template ../buf.dart.gen.yaml ../bitwindow/server
    buf generate --template ../buf.dart.gen.yaml https://github.com/barebitcoin/btc-buf.git
    buf generate --template ../buf.dart.gen.yaml ../sidechain-orchestrator
