import 'package:get_it/get_it.dart';
import 'package:sail_ui/sail_ui.dart';

/// Provider for BitNames configuration settings.
class BitnamesConfProvider extends GenericSidechainConfProvider {
  BitnamesConfProvider._create();

  static Future<BitnamesConfProvider> create() async {
    final instance = BitnamesConfProvider._create();
    await instance.initialize();
    return instance;
  }

  @override
  String get appName => 'BitNames';

  @override
  String get configFileName => 'bitnames.conf';

  @override
  String getDataDir() => BitNames().datadir();

  @override
  Map<String, String> getNetworkPorts(String network) {
    switch (network) {
      case 'regtest':
        return {
          'rpc-addr': '127.0.0.1:16002',
          'net-addr': '0.0.0.0:14002',
          'zmq-addr': '127.0.0.1:38002',
          'mainchain-grpc-port': '50051',
        };
      case 'signet':
      default:
        return {
          'rpc-addr': '127.0.0.1:6002',
          'net-addr': '0.0.0.0:4002',
          'zmq-addr': '127.0.0.1:28002',
          'mainchain-grpc-port': '50051',
        };
    }
  }

  @override
  String getDefaultConfig() {
    String network = 'signet';
    try {
      final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
      network = switch (bitcoinConfProvider.network) {
        BitcoinNetwork.BITCOIN_NETWORK_SIGNET => 'signet',
        BitcoinNetwork.BITCOIN_NETWORK_REGTEST => 'regtest',
        _ => 'signet',
      };
    } catch (_) {}

    final ports = getNetworkPorts(network);

    return '''# BitNames Configuration - Generated by BitNames App
# These settings are converted to CLI arguments when BitNames starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Network (signet or regtest)
network=$network

# RPC server address
rpc-addr=${ports['rpc-addr']}

# P2P networking address
net-addr=${ports['net-addr']}

# ZMQ pub/sub address
zmq-addr=${ports['zmq-addr']}

# Mainchain (Enforcer) gRPC connection
mainchain-grpc-host=127.0.0.1
mainchain-grpc-port=${ports['mainchain-grpc-port']}
''';
  }
}
