format:
   find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

gen:
    buf generate ../../drivechain-server

gen-enforcer:
    buf generate --template buf.gen.yaml https://github.com/LayerTwo-Labs/cusf_sidechain_proto.git
