fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

lint: format fix

gen:
    echo "to generate stuff for bitwindow, go into sail_ui and run just gen"

clean:
    rm assets/bin/*

download:
    bash scripts/download-binaries.sh macos

run: download
    flutter run -d macos
