name: faucet
description: "a drivechain faucet"
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # internal packages
  sail_ui:
    path: ../sail_ui

  auto_route: ^9.3.0+1
  fixnum: ^1.1.1
  cupertino_icons: ^1.0.8
  stacked: ^3.4.3
  get_it: ^7.7.0
  logger: ^2.5.0
  http: ^1.3.0
  intl: ^0.20.2
  protobuf: ^3.1.0
  meta: ^1.16.0
  connectrpc: ^0.3.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6

  auto_route_generator: ^9.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true