import 'package:get_it/get_it.dart';
import 'package:sail_ui/sail_ui.dart';

/// Provider for Inquisition configuration settings.
/// In backend mode, uses BackendSidechainConfProvider (RPC-backed).
/// In frontend mode, uses the file-based implementation directly.
class InquisitionConfProvider extends GenericSidechainConfProvider {
  InquisitionConfProvider._create();

  static Future<GenericSidechainConfProvider> create() async {
    final source = InquisitionConfProvider._create();
    return BackendSidechainConfProvider.fromProvider(source, sidechainName: 'inquisition');
  }

  @override
  String get appName => 'Inquisition';

  @override
  String get configFileName => 'inquisition.conf';

  @override
  String getDataDir() => Inquisition().datadir();

  @override
  List<String> get skippedCliKeys => ['network'];

  @override
  Map<String, String> getNetworkPorts(String network) {
    switch (network) {
      case 'regtest':
        return {
          'rpc-addr': '127.0.0.1:16009',
          'net-addr': '0.0.0.0:14009',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'mainnet':
        return {
          'rpc-addr': '127.0.0.1:26009',
          'net-addr': '0.0.0.0:24009',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
      case 'signet':
      default:
        return {
          'rpc-addr': '127.0.0.1:6009',
          'net-addr': '0.0.0.0:4009',
          'mainchain-grpc-url': 'http://localhost:50051',
        };
    }
  }

  @override
  String getDefaultConfig() {
    String network = 'signet';
    try {
      final bitcoinConfProvider = GetIt.I.get<BitcoinConfProvider>();
      network = switch (bitcoinConfProvider.network) {
        BitcoinNetwork.BITCOIN_NETWORK_SIGNET => 'signet',
        BitcoinNetwork.BITCOIN_NETWORK_REGTEST => 'regtest',
        BitcoinNetwork.BITCOIN_NETWORK_FORKNET || BitcoinNetwork.BITCOIN_NETWORK_DRYNET => 'mainnet',
        _ => 'signet',
      };
    } catch (_) {}

    final ports = getNetworkPorts(network);

    return '''# Inquisition Configuration - Generated by Inquisition App
# These settings are converted to CLI arguments when Inquisition starts.

# Run in headless mode (no GUI)
headless=true

# Log level for console output
log-level=DEBUG

# Log level for file output
log-level-file=WARN

# Network (signet or regtest)
network=$network

# RPC server address
rpc-addr=${ports['rpc-addr']}

# P2P networking address
net-addr=${ports['net-addr']}

# Mainchain (Enforcer) gRPC connection URL
mainchain-grpc-url=${ports['mainchain-grpc-url']}
''';
  }
}
