fix:
    dart fix --apply

format:
    find . -name "*.dart" -not -path "./lib/gen/*" | xargs dart format -l 120

lint: format fix

run:
    #!/usr/bin/env bash
    echo "What chain do you want to boot into?"
    echo "[1]: zcash"
    echo "[2]: thunder"
    echo "[3]: bitnames"
    read -p "Enter choice [1-2]: " choice

    case $choice in
        1) chain="zcash" ;;
        2) chain="thunder" ;;
        3) chain="bitnames" ;;
        *) echo "Invalid choice, defaulting to zcash"; chain="zcash" ;;
    esac

    case "$(uname -s)" in
        Darwin*)  flutter run -d macos --dart-define=SIDESAIL_CHAIN=$chain ;;    # macOS
        Linux*)   flutter run -d linux --dart-define=SIDESAIL_CHAIN=$chain ;;    # Linux
        MINGW*|MSYS*|CYGWIN*)  flutter run -d windows --dart-define=SIDESAIL_CHAIN=$chain ;; # Windows
        *)        echo "Unknown operating system" && exit 1 ;;
    esac
