name: Drivechain Server

on:
  pull_request:
    branches: [master]
    paths:
      - 'drivechain-server/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: drivechain-server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.36.0
      - uses: bufbuild/buf-lint-action@v1.1.1
        with:
          input: drivechain-server

      - name: verify Proto files are formatted correctly
        run: buf format --exit-code proto

  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: drivechain-server
          version: latest

  go-build:
    name: go-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: drivechain-server
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build bdk-cli
        run: |
          just build-bdk-cli
          mv bin/bdk-cli${{ runner.os == 'Windows' && '.exe' || '' }} bin/bdk-cli${{ runner.os == 'Windows' && '.exe' || '' }}-${{ runner.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: bdk-cli${{ runner.os == 'Windows' && '.exe' || '' }}-${{ runner.os }}
          path: drivechain-server/bin
          if-no-files-found: error

      - name: Build drivechain-server
        run: |
          just build-go
          mv bin/drivechain-server bin/drivechain-server-${{ runner.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: drivechain-server-${{ runner.os }}
          path: drivechain-server/bin
          if-no-files-found: error
